### ISSUE TITLE
Not working for https and also not working for http!

### ISSUE THREAD

**Issue by ToxicalNoob3062** [Dreaming-Codes/axios-tauri-http-adapter#2]
code:

 (async () => {
    const res = await client.get("https://dummyjson.com/posts/1");
    console.log(res.data);
  })();

for https:
Error: TypeError: undefined is not an object (evaluating 'response.rid')

for http:
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'response.rid')

**Comment by ToxicalNoob3062** [comment]
> code:
> 
> (async () => { const res = await client.get("https://dummyjson.com/posts/1"); console.log(res.data); })();
> 
> for https: Error: TypeError: undefined is not an object (evaluating 'response.rid')
> 
> for http: Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'response.rid')

if anyone is also facing the same issue should try this package: [fetchify-axios](https://www.npmjs.com/package/fetchify-axios)

**Comment by Dreaming-Codes** [comment]
Are you using tauri beta?

**Comment by ToxicalNoob3062** [comment]
> Are you using tauri beta?

Yes, I've installed the latest beta version of Tauri v2! However, since you took a while to respond, I ended up creating my own package. Additionally, I found your coding style relies too much on dependencies that aren't directly related to the fetch interface provided by the plugin. Consequently, I found it more convenient to develop my own solution. But you can improve this for future users!

**Comment by Dreaming-Codes** [comment]
> Additionally, I found your coding style relies too much on dependencies that aren't directly related to the fetch interface provided by the plugin.

I intentionally avoided using their fetch interfaces due to how they implemented it, particularly how they handle headers like cookies, stripping them away and voiding my use case. By the way, the error you were experiencing is due to the fact that they constantly change the way you're supposed to get a callback from Tauri.
